### ISSUE TITLE
Icons for .h and .cpp files?

### ISSUE THREAD

**Issue by Gruntfuggly** [alexesprit/vscode-unfancy-file-icons#1]
I really like the idea of this - after all, you just really need a way to quickly distinguish the files in the view.

However, could you add something to differentiate between .h and .cpp files (and maybe a few others?):
![image](https://user-images.githubusercontent.com/376658/70041671-77b78080-15b5-11ea-977d-f31d027ae67e.png)

It is working BTW, I can see icons for .gitignore and .sh, etc. :grin:

**Comment by alexesprit** [comment]
Hi! Sure, I'll add icons for C/C++ source files.

**Comment by Gruntfuggly** [comment]
Hi - did you have a chance to add this? I've seen a few new versions, but the .h and .cpp icons are still the same... Thanks!

**Comment by alexesprit** [comment]
:O It works for me. What exactly version have you installed? Is it from VS Marketplace?
![image](https://user-images.githubusercontent.com/1119267/70523936-22e7ad00-1b55-11ea-9d37-dd9ed32160ac.png)

**Comment by alexesprit** [comment]
@Gruntfuggly I probably misunderstood the issue.

> However, could you add something to differentiate between .h and .cpp files (and maybe a few others?)

> Hi - did you have a chance to add this? I've seen a few new versions, but the .h and .cpp icons are still the same... Thanks!

Do you suggest to use the "source" icon (green `file-code` Octicon like on the screenshot above) for both `cpp` and `h` files?

Or do you want to get icons for these files with some variation (e.g. a green icon for `cpp`, and a yellow icon for `h`) to distinguish source files and headers?

**Comment by Gruntfuggly** [comment]
Different colours would be great (maybe more contrasting than yellow and green though). I don't think there is any sensible alternative icon, apart from maybe use 'file' for .h and 'file-code' for .cpp?

**Comment by alexesprit** [comment]
I'll keep a way with different colors for `cpp` (green) and `h` (yellow) files.

> (maybe more contrasting than yellow and green though)

To be honest, I don't want to break rules of the original icon package. A yellow color is used for templates; header files are not templates, though, but yellow color fits better than others.

**Comment by Gruntfuggly** [comment]
OK, no problem. As long as they're not the same that's good for me! :grin:
