### ISSUE TITLE
Icons corrupted on OSX

### ISSUE THREAD

**Issue by Gruntfuggly** [alexesprit/vscode-unfancy-file-icons#3]
I love these icons - I use them at work on a Windows install and an Ubuntu install, but my OSX install at home seems to have a problem:
<img width="505" alt="Screenshot 2020-01-15 at 21 46 30" src="https://user-images.githubusercontent.com/376658/72474510-d2f9a700-37e0-11ea-8a07-85101218746f.png">
If I swap back to other icon sets it fine?

**Comment by alexesprit** [comment]
@Gruntfuggly could you check the extension from this zip package and tell if it works on OSX for you?
[vscode-unfancy-file-icons-2.2.0.zip](https://github.com/alexesprit/vscode-unfancy-file-icons/files/4073411/vscode-unfancy-file-icons-2.2.0.zip)

I use modified Octicons webfont from zypA13510/octicons-webfont that could be broken on OSX.

The extension from that zip package contains Octicons webfont w/o any modifications.

**Comment by Gruntfuggly** [comment]
Unfortunately it still looks the same. Is there anything else I can try?

**Comment by alexesprit** [comment]
@Gruntfuggly I think the only solution is to use svg icons instead of webfonts. I'll let you know when I have the experimental extension to test changes on OSX.

**Comment by Gruntfuggly** [comment]
Ok, great. Let me know - happy to test anything you need.

**Comment by alexesprit** [comment]
@Gruntfuggly Could you check this one? It's not ready for normal use, though.
[vscode-unfancy-file-icons-2.2.0.zip](https://github.com/alexesprit/vscode-unfancy-file-icons/files/4073818/vscode-unfancy-file-icons-2.2.0.zip)

**Comment by alexesprit** [comment]
Different variations of webfont format:
[vscode-unfancy-file-icons-font.zip](https://github.com/alexesprit/vscode-unfancy-file-icons/files/4073860/vscode-unfancy-file-icons-font.zip)

Please let me know if anyone of them works fine for you.

**Comment by Gruntfuggly** [comment]
The eot, woff2 and ttf display in the correct place, but are all coloured squares. The svgfont is the same as before.

**Comment by alexesprit** [comment]
@Gruntfuggly could you check this one?
[vscode-unfancy-file-icons.zip](https://github.com/alexesprit/vscode-unfancy-file-icons/files/4083042/vscode-unfancy-file-icons.zip)

Works fine for me on both Windows 10 and Mac OS Catalina (on VMWare, though).

**Comment by Gruntfuggly** [comment]
Yes, works now ! Thank you! 😁

**Comment by alexesprit** [comment]
@Gruntfuggly thanks for the info! I'm glad it's working for you.

I will add some changes and will publish the new version with the fixed font (it also uses valid SVG icons).

**Comment by alexesprit** [comment]
v2.3.0 should contain the fixed Octicons webfont.
