### ISSUE TITLE
Search Editor tab icon is incorrect

### ISSUE THREAD

**Issue by swrobel** [alexesprit/vscode-unfancy-file-icons#6]
VSCode: 1.49.0 on macOS
Unfancy: 3.10.0

I see this was added to this theme at some point in the past, but it doesn't seem to be working...

Unfancy Codicons:
<img width="187" alt="Screen Shot 2020-09-15 at 9 40 11 AM" src="https://user-images.githubusercontent.com/157270/93239489-b4fd9100-f737-11ea-8ce8-3988f905e59c.png">

SETI icons:
<img width="185" alt="Screen Shot 2020-09-15 at 9 40 25 AM" src="https://user-images.githubusercontent.com/157270/93239477-b202a080-f737-11ea-9cb5-c5221fb00e55.png">

**Comment by alexesprit** [comment]
Good catch! I'll try to fix it.

Interesting, the magnifier icon is displayed for the search saved to a file.

**Comment by alexesprit** [comment]
Should be fixed in v3.12.0. It would be great if you confirm it's fixed for you.

![image](https://user-images.githubusercontent.com/1119267/93247813-90390600-f797-11ea-9bdb-a785d3ea7dda.png)

**Comment by swrobel** [comment]
It's fixed, but would it be too much to ask for basically any other color besides green? Maybe just gray, or perhaps cyan?

**Comment by alexesprit** [comment]
I think it could be changed to tha grey color. Btw, what's wrong with the green color?

**Comment by swrobel** [comment]
Apologies, I should've been clear about that. Since green is source files, the majority of my open tabs are already that color, making it hard to visually distinguish.

**Comment by alexesprit** [comment]
> Since green is source files, the majority of my open tabs are already that color, making it hard to visually distinguish.

That makes the sense. I will change the color to gray in the next version.

**Comment by alexesprit** [comment]
@swrobel I've published v3.12.1 which includes gray color for the search icon.
